language: rust
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
cache: cargo
sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - libudev-dev 

# ex: set tabstop=2 sts=2 sw=2 expandtab
