[package]
name = "mavlink-msp-bridge"
version = "0.0.1"
authors = ["wucke13 <wucke13@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = "2"
crc-any = "2"
env_logger = "0"
#lazy_static = "1.3.0"
log = "0"
mavlink = "0"
serialport = "3"

[dev-dependencies]
rand = "0.7"
