[package]
name = "mavlink-msp-bridge"
version = "0.0.1"
authors = ["wucke13 <wucke13@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = "2"
crc-any = "1.1"
env_logger = "0.6"
#lazy_static = "1.3.0"
log = "0.4"
mavlink = "0.5"
serialport = "3.2"

[dev-dependencies]
rand = "0.7"
